name: New commits on an approved pull request OR PR Approved

on:
  push:
  pull_request_review:
    types: [submitted]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo review state ${{ github.event.review.state }}

      - uses: 8BitJonny/gh-get-current-pr@2.1.3
        id: PR

      - run: echo "PR ${prNumber} ${prTitle} at ${prUrl} is ${prJSON}"
        if: steps.PR.outcome == 'success'
        env:
          prJSON: ${{ toJSON(fromJSON(steps.PR.outputs.pr)) }}
          prNumber: ${{ steps.PR.outputs.number }}
          prUrl: ${{ steps.PR.outputs.pr_url }}
          prTitle: ${{ steps.PR.outputs.pr_title }}

      - run: echo "PR_DRAFT=$(jq -r '.[].draft' <<< ${{ steps.PR.outputs.pr }}" >> $GITHUB_OUTPUT
        if: steps.PR.outcome == 'success'
        id: pr_draft

      - run: echo "the pull request is not anymore in mode draft"
        if: steps.pr_draft.outputs.PR_DRAFT == 'false'

      - run: |
          curl --silent \
            --show-error \
            --request GET \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --url https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${prNumber}/reviews > reviews.json
          cat reviews.json
          jq -r '.[].state' .github/workflows/reviews.json | grep APPROVED ; [[ $? -eq 0 ]] && pr_approved=true || approved=false
          echo "PR_APPROVED=${pr_approved}" >> $GITHUB_OUTPUT
        id: pr_approved
        env:
          prNumber: ${{ steps.PR.outputs.number }}

      - run: echo "the pull request is not anymore in mode draft"
        if: steps.pr_approved.outputs.PR_APPROVED == 'false'
